# Generated by Django 6.0.6 on 2026-07-06 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_coach", "0001_initial"),
        ("interactions", "0003_account_deletion_support"),
        ("posts", "0004_account_deletion_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CivilityPromptEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[("HOSTILE_LANGUAGE", "Hostile language"), ("NONE", "None")],
                        max_length=32,
                    ),
                ),
                ("prompt_shown", models.BooleanField(default=True)),
                (
                    "user_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EDITED", "Edited"),
                            ("POSTED_ANYWAY", "Posted anyway"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("edited_after_prompt", models.BooleanField(default=False)),
                ("original_text_hash", models.CharField(max_length=64)),
                ("final_text_hash", models.CharField(blank=True, max_length=64)),
                ("is_finalized", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="civility_prompt_events",
                        to="posts.post",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="civility_prompt_events",
                        to="interactions.reply",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="civility_prompt_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
