# Generated by Django 6.0.6 on 2026-07-06 01:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "posts",
            "0002_rename_posts_post_created_870fe2_idx_posts_post_created_dadbfe_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("FULL", "Full"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("location_label", models.CharField(blank=True, max_length=200)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "verification_mode",
                    models.CharField(
                        choices=[
                            ("SELF_REPORTED", "Self reported"),
                            ("CREATOR_CONFIRMED", "Creator confirmed"),
                            ("RECIPIENT_CONFIRMED", "Recipient confirmed"),
                            ("NO_VERIFICATION", "No verification"),
                        ],
                        default="SELF_REPORTED",
                        max_length=24,
                    ),
                ),
                ("completion_instructions", models.TextField(blank=True, max_length=1000)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_opportunity",
                        to="posts.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=280)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="prosocial_actions.actionopportunity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SAVED", "Saved"),
                            ("COMMITTED", "Committed"),
                            ("COMPLETION_SUBMITTED", "Completion submitted"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="SAVED",
                        max_length=24,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("reminder_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("reminders_enabled", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                ("private_note", models.TextField(blank=True, max_length=500)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="prosocial_actions.actionopportunity",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="prosocial_actions.commitment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompletionSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("participant_note", models.TextField(blank=True, max_length=1000)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("NOT_REQUIRED", "Not required"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("reviewer_note", models.TextField(blank=True, max_length=500)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commitment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_submission",
                        to="prosocial_actions.commitment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completion_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="actionopportunity",
            index=models.Index(
                fields=["status", "starts_at"], name="prosocial_a_status_d46b21_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="actioninvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("action", "inviter", "invitee"),
                name="unique_pending_invitation",
            ),
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=models.Index(
                fields=["participant", "status"], name="prosocial_a_partici_9d2525_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="commitment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["SAVED", "COMMITTED", "COMPLETION_SUBMITTED"])),
                fields=("action", "participant"),
                name="unique_active_commitment_per_action",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionacknowledgement",
            constraint=models.UniqueConstraint(
                fields=("commitment", "sender"), name="unique_acknowledgement_per_sender"
            ),
        ),
    ]
