# Generated by Django 6.0.6 on 2026-07-06 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("interactions", "0002_alter_notification_kind_prosocialreaction"),
        ("posts", "0003_post_guild_post_thread_type_post_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTrustProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "helper_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMPATHIZER", "Empathizer"),
                            ("SAGE", "Sage"),
                            ("BUILDER", "Builder"),
                            ("GUIDE", "Guide"),
                            ("CONNECTOR", "Connector"),
                        ],
                        max_length=16,
                    ),
                ),
                ("helper_style_completed_at", models.DateTimeField(blank=True, null=True)),
                ("engagement_trust_score", models.FloatField(default=0.0)),
                ("popularity_trust_score", models.FloatField(default=0.0)),
                ("contribution_score", models.FloatField(default=0.0)),
                (
                    "score_visibility",
                    models.CharField(
                        choices=[
                            ("HIDDEN", "Hidden"),
                            ("RANGE", "Range only"),
                            ("EXACT", "Exact score"),
                        ],
                        default="HIDDEN",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PeerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("HELPED_ME", "This helped me"),
                            ("HELPFUL", "Helpful"),
                            ("SUPPORTIVE", "Supportive"),
                            ("INSIGHTFUL", "Insightful"),
                            ("ESCALATORY", "Escalatory"),
                            ("DISMISSIVE", "Dismissive"),
                            ("SPAMMY", "Spammy"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_positive", models.BooleanField()),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_ratings",
                        to="posts.post",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_ratings",
                        to="interactions.reply",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("post__isnull", False), ("reply__isnull", True)),
                            models.Q(("post__isnull", True), ("reply__isnull", False)),
                            _connector="OR",
                        ),
                        name="peer_rating_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("post__isnull", False)),
                        fields=("rater", "post", "dimension"),
                        name="unique_peer_rating_post",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("reply__isnull", False)),
                        fields=("rater", "reply", "dimension"),
                        name="unique_peer_rating_reply",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PEER_RATING_POSITIVE", "Positive peer rating"),
                            ("PEER_RATING_NEGATIVE", "Negative peer rating"),
                            ("THANK_YOU", "Thank you received"),
                            ("COMMITMENT_VERIFIED", "Commitment verified"),
                            ("CLIP_BY_OTHER", "Content clipped by other"),
                            ("MODERATION_UPHELD", "Report upheld"),
                            ("MODERATION_FRIVOLOUS", "Frivolous report"),
                        ],
                        max_length=32,
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("source_type", models.CharField(blank=True, max_length=32)),
                ("source_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="trust_trust_user_id_8a9ecf_idx"
                    )
                ],
            },
        ),
    ]
