# Generated by Django 6.0.6 on 2026-07-06 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivilegeDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("domain", models.CharField(blank=True, max_length=32)),
                ("criteria", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="usertrustprofile",
            name="auth_strength",
            field=models.CharField(
                choices=[("BASIC", "Basic"), ("MFA", "MFA enabled"), ("STRONG_MFA", "Strong MFA")],
                default="BASIC",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="usertrustprofile",
            name="behavior_score",
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name="usertrustprofile",
            name="identity_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usertrustprofile",
            name="risk_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="usertrustprofile",
            name="role_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="trustevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PEER_RATING_POSITIVE", "Positive peer rating"),
                    ("PEER_RATING_NEGATIVE", "Negative peer rating"),
                    ("PROSOCIAL_REACTION", "Prosocial reaction"),
                    ("THANK_YOU", "Thank you received"),
                    ("COMMITMENT_VERIFIED", "Commitment verified"),
                    ("CLIP_BY_OTHER", "Content clipped by other"),
                    ("MODERATION_UPHELD", "Report upheld"),
                    ("MODERATION_FRIVOLOUS", "Frivolous report"),
                    ("APPEAL_REVERSAL", "Appeal reversal"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="TrustCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cluster_id", models.CharField(max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_cluster",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomainReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("support", "Support"),
                            ("clarity", "Clarity"),
                            ("knowledge", "Knowledge"),
                            ("civility", "Civility"),
                            ("concern", "Concern"),
                        ],
                        max_length=16,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_reputations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "category"), name="unique_domain_reputation"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPrivilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain_scope", models.CharField(blank=True, max_length=64)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "privilege",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_to",
                        to="trust.privilegedefinition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privileges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "privilege", "domain_scope"),
                        name="unique_user_privilege_scope",
                    )
                ],
            },
        ),
    ]
