# Generated by Django 6.0.6 on 2026-07-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_activity_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='common_acti_event_t_f08f09_idx',
            old_name='common_acti_event_t_aed9aa_idx',
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('ACCOUNT_REGISTERED', 'Account registered'), ('LOGIN_SUCCEEDED', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('PROFILE_UPDATED', 'Profile updated'), ('POST_CREATED', 'Post created'), ('POST_UPDATED', 'Post updated'), ('POST_DELETED', 'Post deleted'), ('IMAGE_UPLOAD_REJECTED', 'Image upload rejected'), ('CLIP_CREATED', 'Clip created'), ('COLLECTION_CREATED', 'Collection created'), ('USER_FOLLOWED', 'User followed'), ('POST_FOLLOWED', 'Post followed'), ('GUILD_JOINED', 'Guild joined'), ('MESSAGE_SENT', 'Message sent'), ('PEER_RATING_GIVEN', 'Peer rating given'), ('XP_AWARDED', 'XP awarded'), ('TRUST_SCORE_UPDATED', 'Trust score updated')], max_length=64),
        ),
    ]
