# Generated by Django 6.0.6 on 2026-07-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_common_acti_event_t_aed9aa_idx_common_acti_event_t_f08f09_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('ACCOUNT_REGISTERED', 'Account registered'), ('ACCOUNT_DELETION_REQUESTED', 'Account deletion requested'), ('ACCOUNT_DELETION_CANCELLED', 'Account deletion cancelled'), ('ACCOUNT_DELETED', 'Account deleted'), ('LOGIN_SUCCEEDED', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('PROFILE_UPDATED', 'Profile updated'), ('POST_CREATED', 'Post created'), ('POST_UPDATED', 'Post updated'), ('POST_DELETED', 'Post deleted'), ('IMAGE_UPLOAD_REJECTED', 'Image upload rejected'), ('CLIP_CREATED', 'Clip created'), ('COLLECTION_CREATED', 'Collection created'), ('USER_FOLLOWED', 'User followed'), ('POST_FOLLOWED', 'Post followed'), ('GUILD_JOINED', 'Guild joined'), ('MESSAGE_SENT', 'Message sent'), ('PEER_RATING_GIVEN', 'Peer rating given'), ('XP_AWARDED', 'XP awarded'), ('TRUST_SCORE_UPDATED', 'Trust score updated')], max_length=64),
        ),
    ]
