# Generated by Django 6.0.6 on 2026-07-06 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_deletion_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountdeletionrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deletion_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
