# Generated by Django 6.0.6 on 2026-07-06 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('posts', '0003_post_guild_post_thread_type_post_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('REPLY_RECEIVED', 'Reply received'), ('REPLY_TO_REPLY', 'Reply to reply'), ('THANK_YOU_RECEIVED', 'Thank you received'), ('REPORT_RESOLVED', 'Report resolved'), ('USER_FOLLOWED', 'User followed'), ('POST_FOLLOWED', 'Post followed'), ('MESSAGE_RECEIVED', 'Message received'), ('GUILD_INVITE', 'Guild invite'), ('CHALLENGE_COMPLETED', 'Challenge completed'), ('XP_EARNED', 'XP earned'), ('MODERATION_ACTION', 'Moderation action'), ('CRISIS_REVIEW', 'Crisis review')], max_length=32),
        ),
        migrations.CreateModel(
            name='ProsocialReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('CONSTRUCTIVE', 'Constructive'), ('SUPPORTIVE', 'Supportive'), ('INSIGHTFUL', 'Insightful')], max_length=16)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prosocial_reactions', to='posts.post')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prosocial_reactions', to='interactions.reply')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosocial_reactions_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('reply__isnull', True)), models.Q(('post__isnull', True), ('reply__isnull', False)), _connector='OR'), name='prosocial_reaction_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('sender', 'post', 'kind'), name='unique_prosocial_reaction_post'), models.UniqueConstraint(condition=models.Q(('reply__isnull', False)), fields=('sender', 'reply', 'kind'), name='unique_prosocial_reaction_reply')],
            },
        ),
    ]
