# Generated by Django 6.0.6 on 2026-07-06 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0003_account_deletion_support"),
        ("posts", "0004_account_deletion_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prosocialreaction",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("support", "Support"),
                    ("clarity", "Clarity"),
                    ("knowledge", "Knowledge"),
                    ("civility", "Civility"),
                    ("concern", "Concern"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="prosocialreaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("HELPFUL", "Helpful"),
                    ("KIND", "Kind"),
                    ("CLARIFIED", "Clarified"),
                    ("SUPPORTIVE", "Supportive"),
                    ("GOOD_FAITH", "Good faith"),
                    ("NEEDS_CONTEXT", "Needs context"),
                    ("THANKS", "Thanks"),
                    ("CONSTRUCTIVE", "Constructive"),
                    ("INSIGHTFUL", "Insightful"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ContextNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=1000)),
                ("sources", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending review"),
                            ("VISIBLE", "Visible"),
                            ("HIDDEN", "Hidden"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_notes",
                        to="posts.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NoteRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_helpful", models.BooleanField()),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="interactions.contextnote",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RaterTrustGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("group_id", models.CharField(max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rater_trust_group",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="contextnote",
            index=models.Index(fields=["post", "status"], name="interaction_post_id_562c99_idx"),
        ),
        migrations.AddConstraint(
            model_name="noterating",
            constraint=models.UniqueConstraint(fields=("note", "rater"), name="unique_note_rating"),
        ),
    ]
