# Generated by Django 6.0.6 on 2026-07-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="header_image",
            field=models.ImageField(blank=True, upload_to="profiles/headers/"),
        ),
    ]
