# Generated by Django 6.0.6 on 2026-07-06 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_add_profile_header_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopedEndorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_type", models.CharField(max_length=64)),
                ("claim_label", models.CharField(max_length=200)),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("SELF_ASSERTED", "Self-asserted"),
                            ("ORG_ATTESTED", "Organization-attested"),
                            ("DOMAIN_VERIFIED", "Domain-verified"),
                            ("PLATFORM_REVIEWED", "Platform-reviewed"),
                            ("CREDENTIAL", "Credential-backed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("issuer", models.CharField(blank=True, max_length=200)),
                ("scope", models.CharField(blank=True, max_length=200)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="profiles_sc_user_id_7726ed_idx"
                    )
                ],
            },
        ),
    ]
